test:
  services: 
    school: "N:/1000/319456_Lahipalvelujen_saavutettavuus/3_Tarkastelut/Test_data/osm_amenity_school.gpkg"
    restaurant: "N:/1000/319456_Lahipalvelujen_saavutettavuus/3_Tarkastelut/Test_data/osm_amenity_restaurant.gpkg"
    kindergarten: "N:/1000/319456_Lahipalvelujen_saavutettavuus/3_Tarkastelut/Test_data/osm_amenity_kindergarten.gpkg"
  network: "N:/1000/319456_Lahipalvelujen_saavutettavuus/3_Tarkastelut/Test_data/osm_ways_test.gpkg"
  zones: "N:/1000/319456_Lahipalvelujen_saavutettavuus/3_Tarkastelut/Test_data/ruudukko_test.gpkg"
  